---

  - name: Add the yum repo
    yum_repository:
      name: nginx
      description: EPEL nginx repo
      baseurl: "{{ nginx_repo }}"
      gpgcheck: no
      enabled: yes

  - name: Install nginx package
    yum:
      name: nginx
      state: present

  - name: Start and enable service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Update config file
    template:
      src: nginx_conf
      dest: /etc/nginx/nginx.conf
      mode: 0644
      owner: root
      group: root
    notify: restart nginx

  - name: Install apache httpd toolssss
    yum:
      name: httpd-tools
      state: present

  - name: instal passlib
    command: pip install passlib

  - name: create user for authenticatiion
    htpasswd:
      path: "{{ auth_file_path }}"
      name: admin
      password: "{{ admin_passwd }}"
      owner: nginx
      group: nginx
      mode: 0644
    notify: restart nginx
