---
- hosts: "localhost"
  user: vagrant
  become: true
  become_method: sudo

  vars_files:
    - ../vars/main.yml

  handlers:
    - include: ../handlers/main.yml
# - include: package_install.yml
  tasks:
    - include: nginx_install.yml
