---

  - name: Add the yum repo
    yum_repository:
      name: nginx
      description: EPEL nginx repo
      baseurl: "{{ nginx_repo }}"
      gpgcheck: no
      enabled: yes

  - name: Install nginx package
    yum:
      name: nginx
      state: present

  - name: Start and enable service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Update config file
    template:
      src: /home/vagrant/ansible-code/ansible-repo/base-play/templates/nginx_conf
      dest: /etc/nginx/nginx.conf
      mode: 0644
      owner: root
      group: root
    notify: restart nginx
