---
- hosts: localhost
  user: vagrant
  become: true
  become_method: sudo

  tasks:
   - name: "install git"
     yum:
      name: git
      state: present
 
   - name: "install ntp"
     yum:
      name: ntp
      state: present
   - name: "install httpd"
     yum:
      name: httpd
      state: present
